;Using subroutine, find the factorial of a number. 
	AREA FACTORIALSUB, CODE, READONLY
	ENTRY
MAIN
	LDR R0,NUM ; LOAD THE NUMBER
	LDR R3,=1 ;LOAD THE REGISTER VALUE OF R3 TO 1
	BL FACT ;CALL SUB-ROUTINE TO CALCULATE THE FACTORIAL 
	LDR R4,=0X40000000 ;LOAD THE ADDRESS
	STR R3,[R4] ;STORE RESULT IN MEMORY

FACT
	CMP R0,#1 ;CHECK IF THE NUMBER IS EQUAL TO 1
	BXEQ LR ;RETURN TO INSTRUCTION STORED IN LINK REGISTER
	MUL R5,R3,R0 ;MULTIPLY
	MOV R3,R5 ;MOVE CONTENTS
	SUB R0,#1 ;DRCREMENT THE NUMBER
	B FACT ;ITERATIVE PROCESS
STOP B STOP	;INFINITE LOOP
NUM DCD 5 ;ENTER THE NUMBER TO FIND ITS FACTORIAL	
	END ;END OF EXECUTION
		
