;Find the square root of a number present in 0x40000000.Store the result back in 0x40000030	
	AREA SQUARENUM, CODE, READONLY
	ENTRY
MAIN
	LDR R1,=0X40000000 ;LOAD ADDRESS
	LDR R1,[R1]	;LOAD DATA FROM ADDRESS
	LDR R2,=1 ; FINDS THE NEAREST SQUARE TO THE GIVEN NUMBER
SQRT MUL R3,R2,R2 ;BEGINS WITH 1,4,9...
     CMP R3,R1	; COMPARES GIVEN NUMBER WITH ITS SQUARE
     BEQ STORE  ; IF EQUAL STORES THE VALUE IN DESTINATION ADDRESS
     BGT DONE	; IF GREATER , DECREMENTS VALUE OF R2 AND STORES IN DESTINATION ADDRESS
	ADD R2,#1
	B SQRT ; BRANCH TO SQRT
DONE	 
	SUB R2,#1
STORE 
	LDR R4,=0X40000030 ; R4 HOLDS THE DESTINATION ADDRESS
	STR R2,[R4] 
STOP B STOP ; INFINITE LOOP
	END ;END OF EXECUTION
