;Consider an array of 5 32-numbers present from location 0x4000 0000. Find the sum of these numbers and store back in 0x4000 1000.
	AREA ARRAYOFNUM, CODE, READONLY
	ENTRY

MAIN
	LDR R1,=0X40000000 ; LOAD THE ADDRESS VALUE TO R1
	LDR R3,=5; ;HOLDS THE SIZE OF THE ARRAY
	LDR R5,[R1] ;LOAD CONTENTS OF R1 TO R5
SUM	CMP R3,#0 ;CHECK IF SIZE EQUALS 0
	BEQ DONE ;IF EQUAL BRANCH TO DONE 
	ADD R2,R2,R5 ;ADD CONTENTS OF R5 AND R2 AND STORE IN R2
	SUB R3,#1 ;DECREMENT THE COUNT
	LDR R5,[R1,#4]! ; PRE-INDEX INCREMENT 
	B SUM ;GO TO SUM 
DONE 
	LDR R4,=0X40001000 ;LOAD THE ADDRESS
	STR R2,[R4] ;STORE THE RESULT
STOP B STOP	;INFINITE LOOP
	END ;END OF EXCECUTION