;Convert a given number from 0x4000 0000 hex value to ASCII.	
	AREA HEXTOASCII, CODE, READONLY
	ENTRY
main
	LDR R0,=0X40000000 ;32-BIT NUMBER 
	LDR R4,=0x40000100 ;ADDRESS TO STORE THE ASCII VALUE
	LDR R1,[R0] ;LOAD THE CONTENTS IN R0 TO R1
	LDR R2,=8; NO. OF ITERATIONS

CONVERT
	CMP R2,#0 ;CHECK IF COUNT IS ZERO
	BEQ	STOP ;IF EQUAL BRANCH TO STOP
	AND R3,R1,#0XF ; ONLY GET THE LAST NIBBLE
	CMP R3,#0XA ;CHECK IF THE NUMBER IS LESS THAN 10
	BLT SKIP ;IF LESS THE BRANCH TO SKIP
	ADD R3,R3,#"A"-"0"-0XA ;FINDING THE OFFSET
SKIP
	ADD R3,R3,#"0" ;ADD THE ASCII VALUE OF '0' TO THE DIGIT
	STRB R3,[R4],#1 ; STORE THE RESULT IN DESTINATION ADDRESS
	MOV R1,R1,LSR #1 ; RIGHT-SHIFT TO FIND THE NEXT DIGIT
	SUB R2,#1 ;DECREMENT
	B CONVERT  ;ITERATIVE PROCESS
STOP B STOP ;INFINITE LOOP
	END ;END OF EXECUTION
		